"""autogenerate migrations

Revision ID: 1e369ae75e8f
Revises: 
Create Date: 2024-12-15 20:40:12.980613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e369ae75e8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('travel_frequency', sa.Integer(), nullable=False),
    sa.Column('vacation_budget', sa.Integer(), nullable=False),
    sa.Column('proximity_to_mountains', sa.Integer(), nullable=False),
    sa.Column('proximity_to_beaches', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('education_level', sa.String(length=15), nullable=False),
    sa.Column('preferred_activities', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=False),
    sa.Column('favorite_season', sa.String(length=15), nullable=False),
    sa.Column('age_range', sa.String(length=15), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('environmental_concerns', sa.Boolean(), nullable=False),
    sa.Column('preference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=31), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('precision_false', sa.Float(), nullable=False),
    sa.Column('recall_false', sa.Float(), nullable=False),
    sa.Column('f1_score_false', sa.Float(), nullable=False),
    sa.Column('precision_true', sa.Float(), nullable=False),
    sa.Column('recall_true', sa.Float(), nullable=False),
    sa.Column('f1_score_true', sa.Float(), nullable=False),
    sa.Column('conf_matrix_0_0', sa.Integer(), nullable=False),
    sa.Column('conf_matrix_0_1', sa.Integer(), nullable=False),
    sa.Column('conf_matrix_1_0', sa.Integer(), nullable=False),
    sa.Column('conf_matrix_1_1', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'model_name', 'accuracy', 'precision', 'recall', 'f1_score', 'roc_auc', 'precision_false', 'recall_false', 'f1_score_false', 'precision_true', 'recall_true', 'f1_score_true', 'conf_matrix_0_0', 'conf_matrix_0_1', 'conf_matrix_1_0', 'conf_matrix_1_1')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.Column('travel_frequency', sa.Integer(), nullable=False),
    sa.Column('vacation_budget', sa.Integer(), nullable=False),
    sa.Column('proximity_to_mountains', sa.Integer(), nullable=False),
    sa.Column('proximity_to_beaches', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('education_level', sa.String(length=15), nullable=False),
    sa.Column('preferred_activities', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=False),
    sa.Column('favorite_season', sa.String(length=15), nullable=False),
    sa.Column('age_range', sa.String(length=15), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('environmental_concerns', sa.Boolean(), nullable=False),
    sa.Column('preference', sa.Boolean(), nullable=True),
    sa.Column('preference_prediction', sa.Boolean(), nullable=False),
    sa.Column('preference_prediction_probabilities', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('model_metrics')
    op.drop_table('dataset')
    # ### end Alembic commands ###
