import sqlalchemy as sa
from sqlalchemy.sql import func

from database.meta import metadata

model_metrics = sa.Table(
    "model_metrics",
    metadata,
    sa.Column(
        "id",
        sa.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True,
    ),
    sa.Column(
        "model_name",
        sa.String(31),
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "accuracy",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "precision",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "recall",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "f1_score",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "roc_auc",
        sa.Float,
        primary_key=True,
        nullable=True,
    ),
    sa.Column(
        "precision_false",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "recall_false",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "f1_score_false",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "precision_true",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "recall_true",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "f1_score_true",
        sa.Float,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "conf_matrix_0_0",
        sa.Integer,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "conf_matrix_0_1",
        sa.Integer,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "conf_matrix_1_0",
        sa.Integer,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "conf_matrix_1_1",
        sa.Integer,
        primary_key=True,
        nullable=False,
    ),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=func.now(),    # pylint: disable=not-callable
        nullable=False
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=func.now(),    # pylint: disable=not-callable
        onupdate=func.now(),    # pylint: disable=not-callable
        nullable=False
    ),
)
