SUCCESS = "success"
ERROR = "error"
FIELD_ERRORS = "field_errors"
UNAUTHORIZED = "unauthorized"
NOT_FOUND = "not_found"
FORBIDDEN = "forbidden"
SERVER_ERROR = "server_error"
BAD_REQUEST = "bad_request"
